# Generated by Django 4.0.5 on 2022-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Hawaii', 'Hawaii'), ('Kauai', 'Kauai'), ('Lanai', 'Lanai'), ('Maui', 'Maui'), ('Molokai', 'Molokai'), ('Oahu', 'Oahu')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
